# -*- coding: utf-8 -*-
"""odev1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10_GtzJklDkh1oC2akYnJWmIJ8owzQPc6
"""

def inputN():
    n=int (input("Liste oluşturmak için 0-9 arasında bir tam sayı giriniz.. \n"))
    if ( 0 <= n <= 9 ):      
        createList(n)
    else:
        print ("Hatalı giriş yaptınız..!\n")
        inputN()
def createList(n):
    n=list(range(0,1+n)) 
    print ("\nListe oluşturuldu.. ") 
    x=int(len(n))
    q=int(x/2)
    b=n[:q]
    s=n[q:]
    n[q:]=b
    n[:q]=s
    print (n)
    printDoubleArgumant(n)
def printDoubleArgumant(n):
    for i in n:
        if (n[i]%2 == 0):
            print (n[i])
appIsStarted = True
while (appIsStarted == True):
    a = int(input ("Giriş yapmak için 1'e, Çıkmak için 0'a basın.. \n"))
    if a == 1:
        inputN()
    elif a == 0:
        appIsStarted = False
    else :
        print ("Hatalı giriş yaptınız..! \n")