# -*- coding: utf-8 -*-
"""odev2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iYtXokZGzKcnzhJfiTlaBUPVmOaCm3vw
"""

appIsStarted = True
users = {}
def userDelete():
    print("Silmek istediğiniz kullanıcının. \n")
    username  = input("Kullanıcı adı giriniz\n")
    password  = input("Sifre  giriniz\n")
    if (username in users and users[username] == password):
        del users[username]
        print (users)
    else: 
        print ("Hatalı kullanıcı veya adı şifre\n")

def userUpdate():
    print("Düzenlemek istediğiniz kullanıcının. \n")
    username  = input("Kullanıcı adı giriniz\n")
    password  = input("Sifre  giriniz\n")
    if (username in users and users[username] == password):
        password  = input("Yeni şifreni gir\n")
        users[username]=password
        print (users)
    else: 
        print ("Hatalı kullanıcı veya adı şifre\n")


def userLogin():
    print ("Kullanıcı giriş..\n")
    username  = input("Kullanıcı adı giriniz\n")
    password  = input("Sifre  giriniz\n")
    if (username in users and users[username] == password):
        print ("Hoşgeldiniz..\n")
    else:
        print ("Hatalı giriş yaptınız.. \n")




def userRegister():
    print("Yeni kullanıcı kaydı..\n")

    username  = input("Kullanıcı adı giriniz\n")
    password  = input("Sifre  giriniz\n")
    if username in users:
        print ("kullanıcı adı alınmıs\n")
    elif len(password)<4 or len(password)>10 :
        print ("6 ile 10 karakter arası şifre girin..\n")
    elif len(username)<1 or len(username)>10 :
        print ("1 ile 10 karakter arası kullanıcı adı girin..\n")       
    else:
        users[username]=password
        print ("eklendi\n")
        print (users)


while (appIsStarted == True):
    a = int(input ("0 Login \n1 Register \n2 Update \n3 Delete\n4 Exit\n"))
    if a == 0:
        userLogin()
    elif a == 1:
        userRegister()
    elif a == 2:
        userUpdate()
    elif a == 3:
        userDelete()
    elif a == 4:
        appIsStarted = False
    else:
        print ("Hatalı giriş\n")